---
title: "ISLR (2nd Edition)"
author: "Justin Tuyisenge"
date: "June 12, 2025"
output:
  pdf_document:
    toc: true
    toc_depth: 2
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
editor_options: 
  markdown: 
    wrap: 72
---
# Graphics
## Plotting X vs Y data points
```{r}
x <- rnorm(100)
y <- rnorm(100)

plot(x, y)
plot(x, y, 
     xlab = "x-axis",
     ylab = "y-axis",
     main = "X vs Y"
     )
```

## Saving the output of an R plot
```{r}
pdf("figure.pdf")
plot(x, y, col = 'green')
dev.off()
```
## using seq() to create a sequence of numbers
```{r}
x <- seq(1, 10)
print(x)

x <- 1:10
print(x)

x <- seq(-pi, pi, length = 50)
print(x)
```

## using contour() function to produce three-dimensional graph
```{r}
y <- x
f <- outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x,y, f)

contour(x, y, f, nlevels = 45, add = T )
fa <- (f-t(f)) / 2
contour(x,y, fa, nlevels = 15)
```
## using image() function to produce a color-coded plot
```{r}
image(x, y, fa)
persp(x, y, fa, theta = 30)
persp(x, y, fa, theta = 30, phi = 20)
persp(x, y, fa, theta = 30, phi = 70)
persp(x, y, fa, theta = 30, phi = 40)
```
# Indexing Data
































